### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by ForNeVeR** [ForNeVeR/Umov#18]

**Comment by gsomix** [comment]
How about "Umov"?

![220px-nikolay_umov](https://cloud.githubusercontent.com/assets/832449/16489588/444b6f7a-3ee7-11e6-9a86-39f59e70d0a9.jpg)

**Comment by ForNeVeR** [comment]
Yes, I approve that.

**Comment by ForNeVeR** [comment]
Done.
